// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxfarummeappffvjfplm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZmFydW1tZWFwcGZmdmpmcGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDI1NDAsImV4cCI6MjA1NzYxODU0MH0.ygC4QAQEqy8ici9TbeX542-pJMHc3UyIniAiTB6IjHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);